### ISSUE TITLE
Fronte end editing form cannot be saved neither cancelled

### ISSUE THREAD

**Issue by webchun** [Bloggerschmidt/Blank-Bootstrap-Edition#11]
Steps to reproduce :
1. Login as admin in the frontend
2. edit an article.
3. Click on Save or Cancel button
4. Nothing happened

**Comment by webchun** [comment]
I tried to remove these lines and it works. Not sure whether this is a correct approach or not
    unset($doc->_scripts[$this->baseurl .'/media/system/js/mootools-core.js']);
    unset($doc->_scripts[$this->baseurl .'/media/system/js/mootools-more.js']);
    unset($doc->_scripts[$this->baseurl .'/media/system/js/caption.js']);

**Comment by Bloggerschmidt** [comment]
Thanks for reporting. I will work on frontend edition support. Meanwhile, you can assign the protostar template for frontend editing.
