### ISSUE TITLE
BBE 4 - mod_menu override doesn't generate correct output 

### ISSUE THREAD

**Issue by webchun** [Bloggerschmidt/Blank-Bootstrap-Edition#14]
Looks like the mod_menu override doesn't generate correct output so the submenu items are not  displayed

**Comment by Bloggerschmidt** [comment]
In override of mod_breadcrumbs in file default.php the following line should be comment
```
// JHtml::_('bootstrap.tooltip');
```
In source code the file bootstrap.min.js from media folder shouldn't be loaded. It is the js from bootstrap version 2 and not 3.

**Comment by webchun** [comment]
I commented that // JHtml::_('bootstrap.tooltip'); part and nothing happened. The submenus still not showed

**Comment by Bloggerschmidt** [comment]
I just see the line in mod_login default.php, too. Try to comment it there, too.

**Comment by webchun** [comment]
Done. Still no change

**Comment by Bloggerschmidt** [comment]
Do the bootstrap.min.js in source code sill exists?

**Comment by webchun** [comment]
Hmm I saw JHtml::_('bootstrap.tooltip'); on other com_content override () on my setup, but deleting all still not resolve the problem. 

By the way, if this code would create a conflict with BBE 4, wouldn't it will potentially generate error with other components as this code is probably used by other components?

**Comment by Bloggerschmidt** [comment]
Yes, this is the conflict between bootstrap 2 and bootstrap 3. But I think, there is a job for that in joomla dev already. But if you don't want to wait, a good way is to solve it with overrides.

**Comment by webchun** [comment]
Hmm it looks like to risky to use bootstrap 3 with joomla 3 for production at the moment. I see there are issues that will potentially come up later as I probably will use a lot of components later, so maybe the safest way is to stick with bootstrap 2 or using other css framework such as foundation, right? What would you suggest? Thanks

**Comment by Bloggerschmidt** [comment]
yes, the savest way is to stick with bootstrap 2 (welcome to joomla hell). For that you can use blank without bootstrap and can bring foundation or other frontend frameworks in there.

**Comment by webchun** [comment]
doh: I've spent quite a lot of time to explore this bs3 things :\ But it's okay, better to know it sooner. Thanks for your hard work and support @Bloggerschmidt

**Comment by Bloggerschmidt** [comment]
You're welcome.

**Comment by GASOLINE** [comment]
@webchun Why? I make all my clientsites with Joomla 3 & BS3. And off course blank as basis. Very happy with it.

**Comment by webchun** [comment]
@GASOLINE do you use blank without bootstrap or bbe-4 ?

**Comment by webchun** [comment]
If you use blank without bootstrap, do you unset all bootstraps libs (css and js) or simply leaving it there so BS2 will be called by any extension that using it (so in this case you are using both of BS2 and BS3 in one template)?

**Comment by GASOLINE** [comment]
I use bbe3.8 bs edition.

**Comment by webchun** [comment]
Hmm looks like bbe3.8 loads both of bs2 and bs3 libs. What do you think @Bloggerschmidt ? Would you recommend this?

**Comment by Bloggerschmidt** [comment]
Well, bs2 is loaded by default in Joomla! and to work with bs3 your job is to keep bs2 out. So you have to unset the old scripts and add your new scripts and every time an ol' js will appear you have unset it and if this doesn't work to create an override. So, developing with bs3 (without bs2) under J! makes no fun in these days. But it is possible and with overrides even in an acceptable way.
