### ISSUE TITLE
Warning when running npm install

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#18]
Hello,

When installing node dependencies, I'm getting the 2 following warnings:
- deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead
- deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

Regards

**Comment by Bloggerschmidt** [comment]
Thanks for the comment. I will fix this soon with the releas of Blank 4.

**Comment by Delemo** [comment]
Hi Bloggerschmidt,

I realize that, when I'm in the css developmement time, reading the minified style.css file in my browser develpment tool (I'm using the Firefox one) is not always convenient (for example I can't see if a css rule come from Bootstrap or from my custom style sheet).

It could be great if you could choose to not concatenate, minify and uglify css files during the development time and to do so when you are ready to publish your website.

I take the opportunity of this message to thank you for this great template (I realize I haven(t done yet).

Best regards
Simon
