### ISSUE TITLE
<style> code in head.php

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#20]
Hello,
Could you explain, please, what is the purpose of the following css code in inc/head.php file?
<style type="text/stylesheet">
  @-webkit-viewport   { width: device-width; }
  @-moz-viewport      { width: device-width; }
  @-ms-viewport       { width: device-width; }
  @-o-viewport        { width: device-width; }
  @viewport           { width: device-width; }
</style>
Thank you
Simon

**Comment by Bloggerschmidt** [comment]
This is the viewport control via css for initial scaling the view to 100% width of the device (neccessary for mobile devices). The default width is inaccurate. For further reading: [CSS Device Adaption](https://www.w3.org/TR/css-device-adapt/ ).

**Comment by Delemo** [comment]
Thank you for your reply and for the reference,
Do I need to provide some value (in px or in %) replacing 'device-width' string?
Regards

**Comment by Bloggerschmidt** [comment]
No way. It takes the device-width. No additional provision needed here. Leave it as it is. :-)

**Comment by Delemo** [comment]
OK, Thank you

Ah… and thank for BL4NK :)

**Comment by Bloggerschmidt** [comment]
You're welcome!
