### ISSUE TITLE
What is the use of task parameter

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#21]
Hello BloggerSchmidt,

In the <body> class there is a PHP string that test if there is a $task variable.
Could you please explain what is this variable for?

Thank you

PS : Is it OK for you if I keep going asking question through GitHub issues?

**Comment by Bloggerschmidt** [comment]
As a developer you can create your own tasks in Joomla. Anyway there are existing tasks like "edit" e.g. Maybe if you open your site specially in one task you want to display the content in other ways. So I ask for this tasks to create a class and this class you can use for styleing. (-:
