### ISSUE TITLE
Having issues with logic.php, head.php

### ISSUE THREAD

**Issue by kbrookes** [Bloggerschmidt/Blank-Bootstrap-Edition#22]
Hi there,

This is clearly due to my own ignorance but I'm struggling with the logic and head includes and determining how certain scripts are loaded... or not.

1) jQuery loading sometimes, not others
On my home page, jQuery, migrate and no-conflict are added from /media/jui/js - which is pretty much what I'd expect normally. Also as expected, certain scripts are being unset and not appearing (mootools, captions, validate, etc) I really like this a lot BTW.

However navigating to any other page and those scripts are not being loaded into the head.

2) Script load order
Running K2, the k2.frontend.js loads before jQuery, causing a 'jQuery is not defined' console error.

How can we ensure that components scripts requiring jQuery load after jQuery loads?

**Comment by kbrookes** [comment]
Closing this because I understand it now.

It actually does a better job at loading required resources than any other framework I've come across. Even works beautifully with RSForm.

**Comment by Bloggerschmidt** [comment]
Thanks for sharing your experience
