### ISSUE TITLE
Auto compiling of app.js fails to include gulp file .js

### ISSUE THREAD

**Issue by kbrookes** [Bloggerschmidt/Blank-Bootstrap-Edition#24]
Hi there,

I realise this is almost certainly something to do with my understanding of how to work with NPM and the node_modules folder.

That said - I've added additional js files both manually in the /js folder and via npm.

I've had no luck understanding how I should then include those files in node_modules.

But what I have noticed is that if I manually add a js file from /js into the gulp template-js task, any auto-recompile of app.js (like adding new js files, saving script.js, etc) won't include this files in the compile.

If I manually run 'gulp template-js' from the command line however, those files are included in the app.js build.

The next time I make a change that causes app.js to compile, they're not included again.

I'd love to know what's going on here.

K

**Comment by Bloggerschmidt** [comment]
Should be solved with the new release https://github.com/Bloggerschmidt/Blank-Bootstrap-Edition/releases/tag/v5.0.1
