### ISSUE TITLE
BL4NK Bootstrap 4?

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#25]
Hello,
Is there a chance that Bl4nk will be updated with Bootstrap 4?
Regards

**Comment by Bloggerschmidt** [comment]
Maybe -> https://twitter.com/blank_template/status/904712867227869190

**Comment by Bloggerschmidt** [comment]
There will be BL4NK with Twitter Bootstrap 4 https://twitter.com/Bloggerschmidt/status/907256635319611392 :-)
