### ISSUE TITLE
can't include script.js

### ISSUE THREAD

**Issue by benalta64** [Bloggerschmidt/Blank-Bootstrap-Edition#26]
Hello!
Thank you for updating this very usefull template!
I'm not an expert but I can't manage to use the js/script.js file
It looks like its never loaded ...

Thank you for your answer
Regards
BEN

**Comment by imagiax** [comment]
Hi,
I do not know if it's the right method but I added this line 47 in the gulpfile.js:
`gulp.watch(['js/*.js'], ['js']);`
just after:
`gulp.watch(['scss/**/*.scss'], ['sass']);`

**Comment by Bloggerschmidt** [comment]
Yes, to add this line is the correct way. There will be an update shortly. Thank you @imagiax

**Comment by Bloggerschmidt** [comment]
https://github.com/Bloggerschmidt/Blank-Bootstrap-Edition/releases/tag/v5.0.1
