### ISSUE TITLE
An actual blank version?

### ISSUE THREAD

**Issue by JoshWobbles** [Bloggerschmidt/Blank-Bootstrap-Edition#27]
Is there a version that is actually blank? what is with all this node and gulp stuff? Looking for a blank clean slate that i can use bootstrap on without all the side stuff.

**Comment by Bloggerschmidt** [comment]
Node and gulp is using to concatinate and minify your css and js stuff to get a maximum performance for your template. If you are looking for a very basic clean template to start your own experience take a look at https://github.com/Bloggerschmidt/Mini :-) So, BBE (this edition here) is coming with bootstrap and font-awesome and nothing more. Maybe you give it a try.
