### ISSUE TITLE
I get a mixin error for box-shadow

### ISSUE THREAD

**Issue by GASOLINE** [Bloggerschmidt/Blank-Bootstrap-Edition#31]
I'm fairly new to nodejs/Gulp but find it awesome already. I get the idea and it's great, just like your template. However when I start to setup a test to get the hang of it I get an error, which I'm not able to solve.

`events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: scss\bootstrap\_images.scss
Error: no mixin named box-shadow

       Backtrace:
        scss/bootstrap/_images.scss:19
        on line 19 of scss/bootstrap/_images.scss
>>   @include box-shadow($thumbnail-box-shadow);
   -----------^

    at options.error (C:\wamp64\www\joomla\templates\frontend\node_modules\node-sass\lib\index.js:291:26)`

I tried updating BS "npm install bootstrap@4.0.0-alpha.6" but that did not solve the problem.

Any idea what's going wrong here? Rest works like a charm.

**Comment by GASOLINE** [comment]
SO I repeated from scratsch to be sure, this is the result:


`C:\wamp64\www\autoagenda\templates\autoagenda18>npm install

> uws@0.14.5 install C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.5.3 install C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Marc\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-57_binding.node

> node-sass@4.5.3 postinstall C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\node-sass
> node scripts/build.js

Binary found at C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN rollback Rolling back readable-stream@2.2.9 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 497 packages in 10.882s


C:\wamp64\www\autoagenda\templates\autoagenda18>gulp
[16:40:26] Using gulpfile C:\wamp64\www\autoagenda\templates\autoagenda18\gulpfile.js
[16:40:26] Starting 'files'...
[16:40:26] Finished 'files' after 7.55 ms
[16:40:26] Starting 'sass'...
[16:40:26] Starting 'js'...
[16:40:26] Finished 'js' after 68 ms

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: scss\main.scss
Error: File to import not found or unreadable: bootstrap/carousel.
       Parent style sheet: C:/wamp64/www/autoagenda/templates/autoagenda18/scss/main.scss
        on line 39 of scss/main.scss
>> @import "bootstrap/carousel";
   ^

    at options.error (C:\wamp64\www\autoagenda\templates\autoagenda18\node_modules\node-sass\lib\index.js:291:26)`

**Comment by Bloggerschmidt** [comment]
Thank you for your report @GASOLINE . The dependant packages should be installed via `npm install`. The errors can be read as local issues.
