### ISSUE TITLE
Update fontawesome free

### ISSUE THREAD

**Issue by GASOLINE** [Bloggerschmidt/Blank-Bootstrap-Edition#37]
How can I update (automatically) to latest version of fontawesome free.
Would be nice because of some new icons.

**Comment by Bloggerschmidt** [comment]
With the new version coming soon it will be update automatically. Thanks for the request.

**Comment by GASOLINE** [comment]
This is really awesome. Thanks a lot.
Already use your template as a base for building templates for my clients for years.  Really appreciate it.
