### ISSUE TITLE
Sind flexbugsfixes and autoprefixer nötig?

### ISSUE THREAD

**Issue by deltapapa01** [Bloggerschmidt/Blank-Bootstrap-Edition#38]
Moin Moin,
ich schreibe jetzt mal in Deutsch, da mir das ein wenig einfacher fällt, kann das aber wenn gewünscht auch gerne nochmal in Englisch formulieren :-)
Ich bin jetzt soweit, das die Umgebung mit npm / gulp incl GitDesktop wunderbar funktioniert. Ich arbeite mich aber noch weiter am Tutorial entlang, also noch lange nicht fertig und eine Menge zu tun. Sorry also, wenn ich vielleicht sehr einfache oder doofe Fragen stelle, aber meine Template Programmierung - Kenntnisse sind noch ziemlich frisch.
Dazu lerne ich parallel noch mit Videos/Anleitungen von LinkedIn, und dort wird im Workflow Bootstrap 4 und Sass incl Gulp mit Autoprefixer und Flexbugsfixes gearbeitet. Du nutzt im Bootstrap-Blank diese Tools nicht, oder? Werden diese in Joomla nicht benötigt oder hat das noch einen anderen Grund? 
Vielen Dank für eine mögliche Antwort,
deltapapa

-----

Good Morning,
I write now in German, because I find it a bit easier, but if you want to express it again in English :-)
I am now ready that the environment with npm / gulp incl GitDesktop works wonderfully. But I'm still working on the tutorial, so far not finished and a lot to do. So sorry, if I ask very simple or stupid questions, but my template programming skills are still pretty fresh.
At the same time I am still learning videos / tutorials from LinkedIn, and here they are working in the workflow Bootstrap 4 and Sass incl Gulp with autoprefixer and Flexbugsfixes. You do not use these tools in bootstrap blank, right? Are these not needed in Joomla or is there another reason?
Thank you for a possible answer,
deltapapa

**Comment by Bloggerschmidt** [comment]
*Autoprefixer* wird genutzt, um die Browser-Präfixe in CSS automatisch zu setzen. Das kann für `animations`, `transition`, `transform`, `grid`, `flex`, `flexbox` und Konsorten evtl. nützlich sein. Dein Hinweis bringt mich dazu, dieses Plugin mit aufzunehmen. Normaler bin ich ein Fan davon, nur soviel wie nötig mit aufzunehmen. Da aber das Grid-System von Bootstrap auf flexbox basiert, ist es hier notwendig. Genauso wie *Flexbugsfixes*, um die Bugs von flexbox zu fixen. Ein Update ist in der Mache. Für Deine vorhandenen Projekte kannst Du es selbst mit aufnehmen. PostCSS kommst dafür zum Einsatz. Öffne dazu eine Konsole mit dem Pfad in Deinem Template-Ordner und führe folgende Befehle nacheinander aus:

```
npm install --save-dev gulp-postcss
```
```
npm install --save-dev autoprefixer
```
```
npm install --save-dev postcss-flexboxfixer
```

Nimm die installierten Plugins als Variable in der gulpfile.js mit auf, um sie in der `sass`-Funktion einzusetzen..

```
const postcss       = require('gulp-postcss');
const autoprefixer  = require('autoprefixer');

...

// CSS
gulp.task('sass', function() {
    return gulp.src(['scss/main.scss'])
        .pipe(sass({outputStyle: 'compressed'}))
        .pipe(postcss([ autoprefixer() ]))
        .pipe(postcss([require('postcss-flexboxfixer')]))
        .pipe(gulp.dest('build'))
        .pipe(browserSync.stream());
});

```

Nach dem Abspeichern kannst Du `gulp` wie gehabt ausführen. Schaue in der Datei main.css im Ordner build nach. Darin findest Du nun die gewünschten Präfixe im CSS.
