### ISSUE TITLE
Fehler im module chrome zur Sidebar

### ISSUE THREAD

**Issue by deltapapa01** [Bloggerschmidt/Blank-Bootstrap-Edition#41]
Moin Moin,
ich bekomme leider, wenn ich das eigene Module Chrome einrichte eine Fehlerseite angezeigt:
![anmerkung1](https://user-images.githubusercontent.com/19833064/47674158-f6720b00-dbb6-11e8-9044-66b0ed5b5998.png)
Leider habe ich keine Ahnung, was da genau falsch sein könnte. Habe den Code vom Module Chrome genau wie in der Vorlage eingebaut.
Ich nutze die Moduleposition Sidebar nicht, aber warum der Fehler jetzt erscheint würde mich schon interessieren.

Vielen Dank, 
deltapapa

---

Good Morning,
Unfortunately, when I set up my own module chrome, I get an error page:
! [Note 1] (https://user-images.githubusercontent.com/19833064/47674158-f6720b00-dbb6-11e8-9044-66b0ed5b5998.png)
Unfortunately, I have no idea what exactly could be wrong. I have the code from the module chrome built exactly like in the book.
I do not use the module position sidebar, but why the error appears now I would be interested.

Many Thanks,
deltapapa

**Comment by qwertz22** [comment]
Es handelt sich um einen Syntax-Fehler. Also hast du dich irgendwo bei der function verschrieben. Zeige lieber den Code.

**Comment by deltapapa01** [comment]
Hi,
das ist der Inhalt von der modules.php:
`<?php defined('_JEXEC') or die;
​
function modChrome_card($module, &$params, &$attribs) {
  if ($module->content) {
    echo "<div class=\"card " . htmlspecialchars($params->get('moduleclass_sfx')) . "\">";
    echo "<div class=\"card-body\">";
    if ($module->showtitle) {
      echo "<h5 class=\"card-title\">" . $module->title . "</h5>";
    }
    echo $module->content;
    echo "</div>";
    echo "</div>";
  }
}
​
?>`

**Comment by qwertz22** [comment]
Wie und wo bindest du diese Datei ein und wie sieht der Aufruf dieser Funktion aus?

**Comment by deltapapa01** [comment]
Hi,
wie im Bootstrap Tutorial unter Content und Sidebar beschrieben. Genauso:
https://docs.blank.rocks/bootstrap-tutorial#content-and-sidebar

**Comment by deltapapa01** [comment]
So, kurzer Nachtrag,
um den Fehler zu finden habe ich Zeile für Zeile neu reinkopiert, die Klammern etwas anders gesetzt, und nun gehts :-)
**Vielen Dank,** Stück für Stück immer weiter zum eigenen Template...
![image](https://user-images.githubusercontent.com/19833064/47700191-e3425800-dc15-11e8-8cc3-a5ba97de9dab.png)

**Comment by Bloggerschmidt** [comment]
Cool.
