### ISSUE TITLE
Error when trying to install Blank

### ISSUE THREAD

**Issue by SimonBloggs** [Bloggerschmidt/Blank-Bootstrap-Edition#42]
Hello Alexander,

I'm trying to install a new template based on Blank 5.5.0a.
After running npm install on the Blank folder I've got the following error:
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0.4
error: pathspec '4.0' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

I've tried with 5.4.2, same error: 
error: pathspec '4.0' did not match any file(s) known to git.

Could you please help me?
Best regards

**Comment by SimonBloggs** [comment]
Hello,

My workaround:
In the package.json file
line #28 
replace `github:gulpjs/gulp#4.0` by `^4.0.0`

Regards

**Comment by Bloggerschmidt** [comment]
Thanks for the find. Fix it with the new version.
