### ISSUE TITLE
jQuery Probleme

### ISSUE THREAD

**Issue by deltapapa01** [Bloggerschmidt/Blank-Bootstrap-Edition#51]
Moin Moin,
ich habe meine Seite fast fertig, aber noch mit jQuery Problemen zu kämpfen.
Ein Problem ist die Integration von JSN Uniform. Dieses bekomme ich nur zum laufen, wenn ich das Unset vom jquery.min.js entferne.
Was aber noch problematischer ist, sobald ich mich einlogge bekomme ich diverse Fehler.
Hat jemand eine Idee, wie ich das jQuery Problem lösen kann?
Ich möchte die Scripte natürlich auch nicht alle doppelt und dreifach laden, aber irgendwie komme ich im Moment überhaupt nicht weiter...

![image](https://user-images.githubusercontent.com/19833064/49574568-0365e500-f941-11e8-9fef-e4b08c2f87ce.png)

**Comment by GASOLINE** [comment]
The problem you face is that you'v added extensions/plugins. These load js files as well. _It's not an issue with the template files_. You could see if removing JSN Uniforms solves your problem. If so, you can check other form extensions. Chronoforms or RScontact.  Added extensions/plugins can give you lot off headaces.

A good way to check is unpublish all added extensions/plugins and switch them on one by one and see what happens.

You can, btw, load all Joomla js files, remove all unset files in logic.php (add // at beginning of line - _//unset($doc->_scripts[$this->baseurl .'/media/jui/js/jquery.min.js']);_  etc). It does not harm, only loads more JS files.

**Comment by deltapapa01** [comment]
Hey thank you,
sorry for the very long delay, i was soooo busy these holidays, and i don't can fix the jquery probs by the way...
So, i will set up this weekend a clean joomla to check out, why my menu etc not working right...

Thank you and with best regards,
deltapapa

I hope, BS5 has not longer jQuery inside, so maybe all these errors are over....
