### ISSUE TITLE
How to insert Font Awesome icon using css pseudo element

### ISSUE THREAD

**Issue by Delemo** [Bloggerschmidt/Blank-Bootstrap-Edition#53]
Hello,

I would like to know how I can access to Font Awesome resources already installed in Bl4nk template.

In other word I would like to avoid to make a new online request while files are already installed in Bl4nk template.

I see that it is easy to insert a FA icon with <fas>, <far>, <fab> tags (in Joomla! articles for example).

But how can insert an icon with css pseudo element ?

I've tried something than:
.nav-link-search {
  &::before {
    content: '\f002';
    font-family: 'Font Awesome 5 Free';
  }
}

But it seems that doesn't work.

Best regards

**Comment by Bloggerschmidt** [comment]
I think you're doing it the right way. 

> Make sure to include the correct weight and unicode value for the icon

(source: Font Awesome [CSS Pseudo-elements](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#define))

**Comment by Delemo** [comment]
Hello Alexander,

Yes adding
 `font-weight: 900; `
solve the problem (curiously `font-weight: 400;` doesn't work)

Thank you

**Comment by GASOLINE** [comment]
In Fontawesome you have Brands And Icons.

For Icons you can use f,e.:

a[href$=".pdf"]:after {
  /* PDF file */
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
  content: "\f1c1";
  margin-left: 5px;
  margin-right: 5px;
  color: grey;
}

or

a[href$=".pdf"]:after {
  /* PDF file */
  font-family: "Font Awesome 5 Free";
  font-weight: 400;
  content: "\f1c1";
  margin-left: 5px;
  margin-right: 5px;
  color: grey;
}

Changes the icon, _outline_ or _filled_.

For brands etc you use 400.

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
