### ISSUE TITLE
500 - JHtml: :jquery not supported. File not found.

### ISSUE THREAD

**Issue by carlos-andres** [Bloggerschmidt/Blank-Bootstrap-Edition#6]
Good Day i´m install the template and when y try to check home page got this error

![image](https://cloud.githubusercontent.com/assets/5489747/5939471/f5200900-a6d1-11e4-9dc7-20c42da1f10d.png)

**Comment by Bloggerschmidt** [comment]
Which Joomla version do you use?

**Comment by carlos-andres** [comment]
Yes i´m use joomla 2.5 because is for an existing project .. btw i change in logic.php the jquery load function and work´s 

Thanks for your response, have a nice day :D
