### ISSUE TITLE
Local Url into template.css

### ISSUE THREAD

**Issue by carlos-andres** [Bloggerschmidt/Blank-Bootstrap-Edition#7]
Good Day, 

please correct the absolute url into template.css for the web fonts, check this screenshot.. thanks in advance

i´m fix them using ``../`` instead of `http://localhost/test/bbe/`

![image](https://cloud.githubusercontent.com/assets/5489747/5939816/dd016a28-a6d4-11e4-9ba5-6509f303eab8.png)

**Comment by Bloggerschmidt** [comment]
maybe a path correction could help. open template.less and add following line:
```less
// Bootstrap
@import "bootstrap/bootstrap.less";
@fa-font-path: "../templates/frontend/fonts";
```

**Comment by carlos-andres** [comment]
Good Day Alexander,

Already i´m made all path change´s into `template.less` but the `template.css` in repository comes with the localhost url into it.

![image](https://cloud.githubusercontent.com/assets/5489747/5940258/b4a2ee14-a6d7-11e4-83c9-0d96251e4983.png)


Thanks
