### ISSUE TITLE
Clear statement of requirement

### ISSUE THREAD

**Issue by bgschaid** [Bloggerschmidt/Blank-Bootstrap-Edition#9]
Would be nice if there was a clear indication that this needs Joomla 3 or better (was looking for a template to upgrade my existing Joomla 2.5-installation. Installed OK, but I get error messages that are usually associated with 3.x-extensions in 2.5-installations)

**Comment by GASOLINE** [comment]
What are your error messages? I don't have problems with 2.5 sites.

**Comment by bgschaid** [comment]
"500 - JHtml: :jquery not supported. File not found." and most answers on Google went in this direction http://forum.joomla.org/viewtopic.php?f=619&t=830737 so I assumed that the version (with missing jQuery) is the problem
Do I need something like http://www.elovaris.at/en/downloads/jquery-includer ?

**Comment by Bloggerschmidt** [comment]
This could be from logic.php line 20
     JHtml::_('jquery.framework');
You could comment this line, but then jquery should be loaded on other way.

**Comment by Bloggerschmidt** [comment]
.. and yes: a clear indication the need joomla 3 is a good point. Thanks.

**Comment by GASOLINE** [comment]
You could use this f.e. http://extensions.joomla.org/extension/jquery-easy
But appearently your making a new template. Than I would advice to upgrade your Joomla to version 3.x. Version 2.5 is outdated.

**Comment by bgschaid** [comment]
Thanks.
I know (that 2.5 is outdated). I was looking for a quick way to make an existing installation (that was set up by someone else) more mobile-friendly. To be honest: if I have to migrate the installation then I'll probably move it to a static PHP-less CMS
